### ISSUE TITLE
Fix KeyError: 'Required Reputation' [Bug]

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/tensorflow#20]
The rest-api script can now be installed as described on the Readme.md.

However, after running the script and making a curl request, the following error appears:

```
127.0.0.1 - - [30/Nov/2022 12:38:42] "GET /predict/60/1500/I%20am%20a%20machine%20learning%20engineer%20with%20python%20and%20java%20knowledge HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Nov/2022 12:38:42] "GET /predict/60/1500/I%20am%20a%20machine%20learning%20engineer%20with%20python%20and%20java%20knowledge HTTP/1.1" 500 -
Files are Updated                     : 126.51371955871582
ERROR:app:Exception on /predict/60/1500/I am a machine learning engineer with python and java knowledge [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 3803, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Required Reputation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/root/tensorflow/restful-api/app.py", line 90, in get
    filtered_reputation = jobs_df[jobs_df["Required Reputation"] < REPUTATION]
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3804, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'Required Reputation'
```

**Comment by stojanov-igor** [comment]
Please do the fix on the following branch

```
git fetch origin
git checkout 20-fix-keyerror-required-reputation-bug
```

**Comment by TutubanaS** [comment]
I fixed the issue, please give it a check

**Comment by stojanov-igor** [comment]
I still get the same error

**Comment by TutubanaS** [comment]
The issue was file related. Can you please use the file I pushed? On the line of error, it must say "Required Reputation" in brackets. The file column name should match to this. When I pulled, this was the issue.

**Comment by stojanov-igor** [comment]
Yes, I pulled everything on this branch and ran it. 

```
 raise KeyError(key) from err
KeyError: 'Required Reputation'
127.0.0.1 - - [02/Dec/2022 16:12:09] "GET /predict/60/1500/I%20am%20a%20machine%20learning%20engineer%20with%20python%20and%20java%20knowledge HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [02/Dec/2022 16:12:09] "GET /predict/60/1500/I%20am%20a%20machine%20learning%20engineer%20with%20python%20and%20java%20knowledge HTTP/1.1" 500 -
```

**Comment by TutubanaS** [comment]
Can you send me a screenshot of the column names in the csv file? If this is not the issue, then let's have a talk online. Right now, I have no problems running the API and I pushed every change.

**Comment by stojanov-igor** [comment]
jobdesc_extended.csv

`,jobdescription,Longitude,Latitude,Budget,Hours Needed,Deadline,Required Reputation,Remaining Time`

**Comment by stojanov-igor** [comment]
It must be differences in the versions of python, pip, or other libraries. 

What versions are you using? Can we fix all versions in the requirments.txt file itself? 

I am using 
`Python 3.8.10`
`pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)`

and all the libraries from `requirments.txt` as defined there.

**Comment by TutubanaS** [comment]
I dont think it is python related since the error is thrown by pandas, stating that it is KeyError. My best assumption is the differences in attribute names, but you say they are the same. Let us have an online meeting sometime soon.

**Comment by TutubanaS** [comment]
I'll make a new push by using df.get to access the columns safely. It is strange that it works locally to me but not on server. Lets check the column names again.
